name: Build

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup
        uses: actions/setup-java@v5.3.0
        with:
          java-version: '25'
          distribution: 'zulu'
          check-latest: true

      - name: Verify
        run: java -version

      - name: Cache
        uses: actions/cache@v5.0.5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew clean build --no-daemon

      - name: Upload
        uses: actions/upload-artifact@v7.0.1
        with:
          name: build
          path: build/libs/
